- name: diffuse
  config:
    color: [0.725, 0.71, 0.68]
- name: diffuse
  config:
    color: [0.161, 0.133, 0.427]
- name: diffuse
  config:
    color: [0.630, 0.065, 0.05]
- name: microfacet
  config:
    color: [0.8, 0.8, 0.8]
    roughness: 0.28
    ext_ior: 1
    int_ior: 1.5
- name: microfacet
  config:
    color: [0.8, 0.8, 0.8]
    roughness: 0.08
    ext_ior: 1
    int_ior: 1.5
- name: diffuse
  config:
    color: [0.8, 0.8, 0.8]
