- name: diffuse
  config:
    color: [0.725, 0.71, 0.68]
- name: diffuse
  config:
    color: [0.161, 0.133, 0.427]
- name: diffuse
  config:
    color: [0.630, 0.065, 0.05]
- name: diffuse
  config:
    color: [0.8, 0.8, 0.4]
- name: diffuse
  config:
    color: [0.4, 0.8, 0.8]
- name: diffuse
  config:
    color: [0.8, 0.8, 0.8]
